### ISSUE TITLE
Add developing content

### ISSUE THREAD

**Issue by damon-vix** [vix-digital/playbook#20]
Add content to the developing section.

**Comment by damon-vix** [comment]
- [ ] Collaboration
- [ ] Version Control
- [ ] Coding Standards
- [ ] Test Driven Development
- [ ] Refactoring
- [ ] Pair Programming
- [ ] Continuous Integration

**Comment by v9Chris** [comment]
Going to start by doing Pair Programming, Refactoring and Continuous Integration

**Comment by damon-vix** [comment]
Ok. I'm writing up Coding Standards, Version Control and Test Driven Development.

**Comment by damon-vix** [comment]
Finished writing up Collaboration, Version Control, Coding Standards and Test Driven Development. See Pull Request #26.

**Comment by v9Chris** [comment]
Last pull request waiting #36 .

Once that's in this can be closed.
